apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dialedin-frontend
spec:
  ingressClassName: nginx
  rules:
    - host: ai.dialedin.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dialchat-frontend-svc
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dialedin-frontend-api
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: ai.dialedin.me
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: dialchat-agent-svc
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dialedin-agent
spec:
  ingressClassName: nginx
  rules:
    - host: api.dialedin.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dialchat-agent-svc
                port:
                  number: 8000